import requests
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from datetime import datetime

OLLAMA_URL = "http://localhost:11434/api/generate"


def generate_report(incident, threat_type):

    prompt = f"""
You are a senior cybersecurity SOC analyst.

Generate a professional network intrusion investigation report.

Incident Details
----------------
Time: {incident['time']}
Prediction: {incident['prediction']}
Threat Type: {threat_type}
Risk Score: {incident['risk_score']}

Network Packet Data
-------------------
{incident['packet']}

Write a structured report with the following sections:

1. Executive Summary
2. Attack Classification
3. Indicators of Compromise
4. Potential Impact
5. Recommended Mitigation Steps
6. Security Analyst Conclusion

Make the explanation technical but clear.
"""

    payload = {
        "model": "mistral",
        "prompt": prompt,
        "stream": False
    }

    try:
        r = requests.post(OLLAMA_URL, json=payload)
        response = r.json()["response"]
        return response

    except Exception as e:
        return f"AI report generation failed: {str(e)}"


# ------------------------------------------------
# PDF REPORT GENERATOR
# ------------------------------------------------

def create_pdf(report_text, filename="incident_report.pdf"):

    c = canvas.Canvas(filename, pagesize=letter)

    width, height = letter
    y = height - 60

    # Title
    c.setFont("Helvetica-Bold", 16)
    c.drawString(40, y, "AI Intrusion Detection Incident Report")

    y -= 40

    c.setFont("Helvetica", 10)

    lines = report_text.split("\n")

    for line in lines:

        c.drawString(40, y, line)

        y -= 16

        if y < 60:
            c.showPage()
            c.setFont("Helvetica", 10)
            y = height - 60

    # Footer
    c.setFont("Helvetica-Oblique", 8)
    c.drawString(40, 30, f"Generated by AI IDS System - {datetime.now()}")

    c.save()

    return filename